[package]
name = "patterns-sys"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
strip = true

[lib]
crate-type = ["cdylib", "rlib", "staticlib"]

[dependencies.patterns]
path = "../"
